openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: bearer
  title: Amazon CodeCatalyst AccessTokens API
  description: <p>Welcome to the Amazon CodeCatalyst API reference. This reference provides descriptions of operations and data types for Amazon CodeCatalyst. You can use the Amazon CodeCatalyst API to work with the following objects. </p> <p>Spaces, by calling the following:</p> <ul> <li> <p> <a>DeleteSpace</a>, which deletes a space.</p> </li> <li> <p> <a>GetSpace</a>, which returns information about a space.</p> </li> <li> <p> <a>GetSubscription</a>, which returns information about the Amazon Web Services account used for billing purposes and the billing plan for the space.</p> </li> <li> <p> <a>ListSpaces</a>, which retrieves a list of spaces.</p> </li> <li> <p> <a>UpdateSpace</a>, which hanges one or more values for a space.</p> </li> </ul> <p>Projects, by calling the following:</p> <ul> <li> <p> <a>CreateProject</a> which creates a project in a specified space.</p> </li> <li> <p> <a>GetProject</a>, which returns information about a project.</p> </li> <li> <p> <a>ListProjects</a>, which retrieves a list of projects in a space.</p> </li> </ul> <p>Users, by calling the following:</p> <ul> <li> <p> <a>GetUserDetails</a>, which returns information about a user in Amazon CodeCatalyst.</p> </li> </ul> <p>Source repositories, by calling the following:</p> <ul> <li> <p> <a>CreateSourceRepository</a>, which creates an empty Git-based source repository in a specified project.</p> </li> <li> <p> <a>CreateSourceRepositoryBranch</a>, which creates a branch in a specified repository where you can work on code.</p> </li> <li> <p> <a>DeleteSourceRepository</a>, which deletes a source repository.</p> </li> <li> <p> <a>GetSourceRepository</a>, which returns information about a source repository.</p> </li> <li> <p> <a>GetSourceRepositoryCloneUrls</a>, which returns information about the URLs that can be used with a Git client to clone a source repository.</p> </li> <li> <p> <a>ListSourceRepositories</a>, which retrieves a list of source repositories in a project.</p> </li> <li> <p> <a>ListSourceRepositoryBranches</a>, which retrieves a list of branches in a source repository.</p> </li> </ul> <p>Dev Environments and the Amazon Web Services Toolkits, by calling the following:</p> <ul> <li> <p> <a>CreateDevEnvironment</a>, which creates a Dev Environment, where you can quickly work on the code stored in the source repositories of your project.</p> </li> <li> <p> <a>DeleteDevEnvironment</a>, which deletes a Dev Environment.</p> </li> <li> <p> <a>GetDevEnvironment</a>, which returns information about a Dev Environment.</p> </li> <li> <p> <a>ListDevEnvironments</a>, which retrieves a list of Dev Environments in a project.</p> </li> <li> <p> <a>ListDevEnvironmentSessions</a>, which retrieves a list of active Dev Environment sessions in a project.</p> </li> <li> <p> <a>StartDevEnvironment</a>, which starts a specified Dev Environment and puts it into an active state.</p> </li> <li> <p> <a>StartDevEnvironmentSession</a>, which starts a session to a specified Dev Environment.</p> </li> <li> <p> <a>StopDevEnvironment</a>, which stops a specified Dev Environment and puts it into an stopped state.</p> </li> <li> <p> <a>StopDevEnvironmentSession</a>, which stops a session for a specified Dev Environment.</p> </li> <li> <p> <a>UpdateDevEnvironment</a>, which changes one or more values for a Dev Environment.</p> </li> </ul> <p>Security, activity, and resource management in Amazon CodeCatalyst, by calling the following:</p> <ul> <li> <p> <a>CreateAccessToken</a>, which creates a personal access token (PAT) for the current user.</p> </li> <li> <p> <a>DeleteAccessToken</a>, which deletes a specified personal access token (PAT).</p> </li> <li> <p> <a>ListAccessTokens</a>, which lists all personal access tokens (PATs) associated with a user.</p> </li> <li> <p> <a>ListEventLogs</a>, which retrieves a list of events that occurred during a specified time period in a space.</p> </li> <li> <p> <a>VerifySession</a>, which verifies whether the calling user has a valid Amazon CodeCatalyst login and session.</p> </li> </ul> <note> <p>If you are using the Amazon CodeCatalyst APIs with an SDK or the CLI, you must configure your computer to work with Amazon CodeCatalyst and single sign-on (SSO). For more information, see <a href="https://docs.aws.amazon.com/codecatalyst/latest/userguide/set-up-cli.html">Setting up to use the CLI with Amazon CodeCatalyst</a> and the SSO documentation for your SDK.</p> </note>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codecatalyst
  x-aws-signingName: codecatalyst
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codecatalyst-2022-09-28.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codecatalyst.global.api.aws
  variables: {}
  description: The general Amazon CodeCatalyst multi-region endpoint
- url: https://codecatalyst.global.api.aws
  variables: {}
  description: The general Amazon CodeCatalyst multi-region endpoint
- url: http://codecatalyst.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon CodeCatalyst endpoint for China (Beijing) and China (Ningxia)
- url: https://codecatalyst.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon CodeCatalyst endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: AccessTokens
paths:
  /v1/accessTokens:
    put:
      operationId: CreateAccessToken
      description: Creates a personal access token (PAT) for the current user. A personal access token (PAT) is similar to a password. It is associated with your user identity for use across all spaces and projects in Amazon CodeCatalyst. You use PATs to access CodeCatalyst from resources that include integrated development environments (IDEs) and Git-based source repositories. PATs represent you in Amazon CodeCatalyst and you can manage them in your user settings.For more information, see <a href="https://docs.aws.amazon.com/codecatalyst/latest/userguide/ipa-tokens-keys.html">Managing personal access tokens in Amazon CodeCatalyst</a>.
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccessTokenResponse'
              examples:
                CreateAccessToken201Example:
                  summary: Default CreateAccessToken 201 response
                  x-microcks-default: true
                  value:
                    secret: example-value
                    name: example-resource
                    expiresTime: example-value
                    accessTokenId: '500123'
        '480':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                CreateAccessToken480Example:
                  summary: Default CreateAccessToken 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                CreateAccessToken481Example:
                  summary: Default CreateAccessToken 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                CreateAccessToken482Example:
                  summary: Default CreateAccessToken 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
              examples:
                CreateAccessToken483Example:
                  summary: Default CreateAccessToken 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                CreateAccessToken484Example:
                  summary: Default CreateAccessToken 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                CreateAccessToken485Example:
                  summary: Default CreateAccessToken 485 response
                  x-microcks-default: true
                  value: example-value
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - name
              properties:
                name:
                  description: The friendly name of the personal access token.
                  type: string
                  minLength: 1
                  maxLength: 100
                expiresTime:
                  description: The date and time the personal access token expires, in coordinated universal time (UTC) timestamp format as specified in <a href="https://www.rfc-editor.org/rfc/rfc3339#section-5.6">RFC 3339</a>.
                  type: string
                  format: date-time
            examples:
              CreateAccessTokenRequestExample:
                summary: Default CreateAccessToken request
                x-microcks-default: true
                value:
                  name: example-resource
                  expiresTime: example-value
      summary: Amazon CodeCatalyst Create Access Token
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - AccessTokens
    post:
      operationId: ListAccessTokens
      description: Lists all personal access tokens (PATs) associated with the user who calls the API. You can only list PATs associated with your Amazon Web Services Builder ID.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAccessTokensResponse'
              examples:
                ListAccessTokens200Example:
                  summary: Default ListAccessTokens 200 response
                  x-microcks-default: true
                  value:
                    items: example-value
                    nextToken: example-value
        '480':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                ListAccessTokens480Example:
                  summary: Default ListAccessTokens 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                ListAccessTokens481Example:
                  summary: Default ListAccessTokens 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                ListAccessTokens482Example:
                  summary: Default ListAccessTokens 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
              examples:
                ListAccessTokens483Example:
                  summary: Default ListAccessTokens 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                ListAccessTokens484Example:
                  summary: Default ListAccessTokens 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListAccessTokens485Example:
                  summary: Default ListAccessTokens 485 response
                  x-microcks-default: true
                  value: example-value
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                maxResults:
                  description: The maximum number of results to show in a single call to this API. If the number of results is larger than the number you specified, the response will include a <code>NextToken</code> element, which you can use to obtain additional results.
                  type: integer
                  maximum: 10
                nextToken:
                  description: A token returned from a call to this API to indicate the next batch of results to return, if any.
                  type: string
                  minLength: 1
                  maxLength: 10000
            examples:
              ListAccessTokensRequestExample:
                summary: Default ListAccessTokens request
                x-microcks-default: true
                value:
                  maxResults: 1
                  nextToken: example-value
      summary: Amazon CodeCatalyst List Access Tokens
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - AccessTokens
  /v1/accessTokens/{id}:
    delete:
      operationId: DeleteAccessToken
      description: Deletes a specified personal access token (PAT). A personal access token can only be deleted by the user who created it.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteAccessTokenResponse'
              examples:
                DeleteAccessToken200Example:
                  summary: Default DeleteAccessToken 200 response
                  x-microcks-default: true
                  value: {}
        '480':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                DeleteAccessToken480Example:
                  summary: Default DeleteAccessToken 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                DeleteAccessToken481Example:
                  summary: Default DeleteAccessToken 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                DeleteAccessToken482Example:
                  summary: Default DeleteAccessToken 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
              examples:
                DeleteAccessToken483Example:
                  summary: Default DeleteAccessToken 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                DeleteAccessToken484Example:
                  summary: Default DeleteAccessToken 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                DeleteAccessToken485Example:
                  summary: Default DeleteAccessToken 485 response
                  x-microcks-default: true
                  value: example-value
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the personal access token to delete. You can find the IDs of all PATs associated with your Amazon Web Services Builder ID in a space by calling <a>ListAccessTokens</a>.
        schema:
          type: string
          minLength: 1
          maxLength: 36
      summary: Amazon CodeCatalyst Delete Access Token
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - AccessTokens
components:
  schemas:
    ThrottlingException: {}
    AccessTokenSummaries:
      type: array
      items:
        $ref: '#/components/schemas/AccessTokenSummary'
    AccessTokenSecret:
      type: string
      minLength: 1
      maxLength: 4000
      format: password
    ServiceQuotaExceededException: {}
    ConflictException: {}
    AccessTokenId:
      type: string
      minLength: 1
      maxLength: 36
    String:
      type: string
    CreateAccessTokenResponse:
      type: object
      required:
      - secret
      - name
      - expiresTime
      - accessTokenId
      properties:
        secret:
          allOf:
          - $ref: '#/components/schemas/AccessTokenSecret'
          - description: The secret value of the personal access token.
        name:
          allOf:
          - $ref: '#/components/schemas/AccessTokenName'
          - description: The friendly name of the personal access token.
        expiresTime:
          allOf:
          - $ref: '#/components/schemas/SyntheticTimestamp_date_time'
          - description: The date and time the personal access token expires, in coordinated universal time (UTC) timestamp format as specified in <a href="https://www.rfc-editor.org/rfc/rfc3339#section-5.6">RFC 3339</a>. If not specified, the default is one year from creation.
        accessTokenId:
          allOf:
          - $ref: '#/components/schemas/AccessTokenId'
          - description: The system-generated unique ID of the access token.
    AccessDeniedException: {}
    AccessTokenName:
      type: string
      minLength: 1
      maxLength: 100
    ListAccessTokensResponse:
      type: object
      required:
      - items
      properties:
        items:
          allOf:
          - $ref: '#/components/schemas/AccessTokenSummaries'
          - description: A list of personal access tokens (PATs) associated with the calling user identity.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A token returned from a call to this API to indicate the next batch of results to return, if any.
    ResourceNotFoundException: {}
    ValidationException: {}
    SyntheticTimestamp_date_time:
      type: string
      format: date-time
    DeleteAccessTokenResponse:
      type: object
      properties: {}
    AccessTokenSummary:
      type: object
      required:
      - id
      - name
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/AccessTokenId'
          - description: The system-generated ID of the personal access token.
        name:
          allOf:
          - $ref: '#/components/schemas/AccessTokenName'
          - description: The friendly name of the personal access token.
        expiresTime:
          allOf:
          - $ref: '#/components/schemas/SyntheticTimestamp_date_time'
          - description: The date and time when the personal access token will expire, in coordinated universal time (UTC) timestamp format as specified in <a href="https://www.rfc-editor.org/rfc/rfc3339#section-5.6">RFC 3339</a>.
      description: Information about a specified personal access token (PAT).
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codecatalyst/
